---
title: "Introducción al Aprendizaje Supervisado"
author: "Harold A. Hernández-Roig (hahernan@est-econ.uc3m.es)"
date: "20-21 Febrero 2020"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib, analytics.c2.bib]
biblio-style: apalike
link-citations: yes
description: "Sesiones 14-15 IV Edición del Big Analytics: de la información al conocimiento."
output:
  bookdown::gitbook
---

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'class', 'caret', 'ISLR', 'ROCR'
), 'packages.bib')
knitr::opts_chunk$set(cache = T)
```

# Introducción

¡Bienvenidos a las sesiones de *Aprendizaje Supervisado (14-15)* del *Big Analytics: de la Información al Conocimiento, IV Ed.*!

La bibliografía fundamental para estas dos sesiones es el libro de [@james2013introduction]. En el mismo, podrán encontrar las principales ideas ya estudiadas, así como ejemplos prácticos sencillos en R (ver el paquete `ISLR` [@R-ISLR]). También recomendamos los libros [@Rebala2019] y [@Burger2018], como material complementario.

Los paquetes de R empleados para ajustar los algoritmos supervisados *K-Nearest-Neighbors*, *Linear Discriminant Analysis (LDA)*, y *Quadratic Discriminant Analysis (QDA)*; son `caret`[@R-caret] y `class`[@R-class]. Para el paquete `caret`, se recomienda además revisar la documentación en [topepo.github.io/caret](http://topepo.github.io/caret/index.html).

La organización del documento corresponde, en general, a la seguida durante las prácticas.

Have fun! :)
